### PR TITLE
[issue-11] implemented kafka <-> elasticsearch interface (pipeline)

### PR DESCRIPTION
**Pull request by KumKeeHyun**
kafka/kafkaPipe.go : consume data from kafka
kafka/processing.go : data processing ( value: [ ]int -> {string : int, string : int, string : int ...} )
kafka/elasticPipe.go : push document to elasticsearch

@joongsukim 
I'm trying to enrich the data in a consumer, not a Raspberry Pi(sensor value data). How about Raspberry Pi managing only mqtt topics?

### CODE REVIEW

**Comment by KumKeeHyun** [comment]
* I know about the need for a configuration file, but I have only temporarily created and tested the setting structure. The web application uses a toml file. Do I need to make the configuration file for Kafka Consumer independent of the web application configuration file?
* I forgot to change to Apache Kafka. I'll fix it next week.

I will implement a websocket connection(used in data processing) and send a pull request again.

**Comment by yoonje** [comment]
- Yes. Make the configuration file for Kafka Consumer independent of the web application configuration file. 
- Please separate the test code or pull request the source that passed the test.

**Comment by KumKeeHyun** [comment]
ok thanks for review my code :)

* Looking at the GitHub documentation,  [confluent-kafka-go](https://github.com/confluentinc/confluent-kafka-go) seems to support Apache Kafka as well.

**Comment by yoonje** [comment]
Okay. Good Luck!

**Pull request closed without merging**
